/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system-wide overview statistics
         * @description Returns aggregate counts for users, clubs, events, and registrations. Requires ADMIN role.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Overview statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["OverviewStats"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get activity and event statistics over time
         * @description Returns monthly breakdown of event creation and registration counts. Requires ADMIN role.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Activity statistics by month */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["ActivityStats"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic search across clubs and events using AI */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Search keywords or natural language query
                         * @example music clubs with beginner-friendly activities
                         */
                        query: string;
                        /**
                         * @description Maximum number of results to return
                         * @default 10
                         */
                        limit?: number;
                    };
                };
            };
            responses: {
                /** @description AI search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @description Ranked list of matching clubs or events */
                            data?: unknown[];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description AI service temporarily unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get personalized club and event recommendations for the current user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Maximum number of recommendations
                         * @default 5
                         */
                        limit?: number;
                    };
                };
            };
            responses: {
                /** @description Personalized recommendations based on user history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @description Recommended clubs and events */
                            data?: unknown[];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description AI service temporarily unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask the AI assistant a question about the portal */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description A natural language question
                         * @example How do I join a club as a new student?
                         */
                        question: string;
                    };
                };
            };
            responses: {
                /** @description AI-generated answer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /** @description The AI's response to the question */
                                answer?: string;
                            };
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description AI service temporarily unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Full name
                         * @example Nguyen Van A
                         */
                        TenNguoiDung: string;
                        /**
                         * Format: email
                         * @description Email address
                         * @example nguyenvana@student.edu.vn
                         */
                        Email: string;
                        /**
                         * @description Password (min 6 characters)
                         * @example secret123
                         */
                        MatKhau: string;
                        /**
                         * @description Student ID (optional)
                         * @example SV001
                         */
                        MaSV?: string;
                        /**
                         * @description Phone number (optional)
                         * @example 0901234567
                         */
                        SDT?: string;
                    };
                };
            };
            responses: {
                /** @description Account created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description Email already in use */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description Email address
                         * @example nguyenvana@student.edu.vn
                         */
                        Email: string;
                        /**
                         * @description Account password
                         * @example secret123
                         */
                        MatKhau: string;
                    };
                };
            };
            responses: {
                /** @description Login successful — returns access and refresh tokens */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description Incorrect email or password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Account is locked or pending approval */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a new access token using a refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description A valid refresh token obtained from login */
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description New access token issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["AuthTokens"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset link via email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example nguyenvana@student.edu.vn
                         */
                        Email: string;
                    };
                };
            };
            responses: {
                /** @description Reset link sent to the email address (if account exists) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password using a token received by email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Reset token from the email link */
                        token: string;
                        /**
                         * @description New password (min 6 characters)
                         * @example newSecret456
                         */
                        MatKhauMoi: string;
                    };
                };
            };
            responses: {
                /** @description Password reset successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"];
                    };
                };
                /** @description Invalid or expired reset token */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently authenticated user's profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["UserProfile"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and invalidate the current access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change password for the authenticated user */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Current password
                         * @example secret123
                         */
                        MatKhauCu: string;
                        /**
                         * @description New password (min 6 characters)
                         * @example newSecret456
                         */
                        MatKhauMoi: string;
                    };
                };
            };
            responses: {
                /** @description Password changed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"];
                    };
                };
                /** @description Wrong current password or validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thong-bao/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a notification to a single user
         * @description Requires ADMIN or CHU_CLB role
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Notification title
                         * @example Event registration confirmed
                         */
                        TieuDe: string;
                        /**
                         * @description Notification body content
                         * @example Your registration for "Tech Club Spring 2025" has been confirmed.
                         */
                        NoiDung: string;
                        /**
                         * @description Target user ID
                         * @example usr_abc123
                         */
                        MaNguoiDung: string;
                        /**
                         * @description Notification type
                         * @default HE_THONG
                         * @enum {string}
                         */
                        LoaiThongBao?: "HE_THONG" | "HOAT_DONG" | "CLB" | "TUYEN_DUNG";
                        /**
                         * @description Delivery channels
                         * @default [
                         *       "IN_APP"
                         *     ]
                         */
                        KenhGui?: ("IN_APP" | "EMAIL" | "SMS")[];
                    };
                };
            };
            responses: {
                /** @description Notification sent successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thong-bao/send-bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a notification to multiple users at once
         * @description Requires ADMIN or CHU_CLB role. Target by user list, club, or all users.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Notification title
                         * @example Upcoming club event reminder
                         */
                        TieuDe: string;
                        /**
                         * @description Notification body
                         * @example Don't forget the coding workshop this Saturday at 9am!
                         */
                        NoiDung: string;
                        /**
                         * @default HE_THONG
                         * @enum {string}
                         */
                        LoaiThongBao?: "HE_THONG" | "HOAT_DONG" | "CLB" | "TUYEN_DUNG";
                        /**
                         * @default [
                         *       "IN_APP"
                         *     ]
                         */
                        KenhGui?: ("IN_APP" | "EMAIL" | "SMS")[];
                        /** @description Specific list of user IDs (optional) */
                        DanhSachNguoiDung?: string[];
                        /** @description Club ID — send to all members of this club (optional) */
                        MaToChuc?: string;
                        /** @description If true, send to all users in the system */
                        TatCa?: boolean;
                        /**
                         * Format: date-time
                         * @description Scheduled send time (optional, ISO 8601)
                         */
                        ThoiGianGui?: string;
                    };
                };
            };
            responses: {
                /** @description Bulk notifications queued successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thong-bao/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get notification statistics for the current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notification counts by status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["NotificationStats"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thong-bao/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark all notifications as read for the current user */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All notifications marked as read */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thong-bao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notifications for the current user */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    limit?: number;
                    /** @description Filter by notification type */
                    LoaiThongBao?: "HE_THONG" | "HOAT_DONG" | "CLB" | "TUYEN_DUNG";
                    /** @description Filter by read status */
                    TrangThai?: "CHUA_DOC" | "DA_DOC";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of notifications */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                items?: components["schemas"]["Notification"][];
                                total?: number;
                                page?: number;
                                limit?: number;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thong-bao/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single notification by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Notification ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notification details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Notification"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a notification */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Notification ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notification deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thong-bao/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark a specific notification as read */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Notification ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notification marked as read */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiSuccess: {
            /** @example true */
            success?: boolean;
            /** @description Response payload */
            data?: unknown;
        };
        ApiError: {
            /** @example false */
            success?: boolean;
            /** @example Error message */
            error?: string;
        };
        UserProfile: {
            /** @description User ID */
            MaNguoiDung?: string;
            /** @description Full name */
            TenNguoiDung?: string;
            /**
             * Format: email
             * @description Email address
             */
            Email?: string;
            /** @description Student ID */
            MaSV?: string | null;
            /** @description Phone number */
            SDT?: string | null;
            /**
             * @description Account type / role
             * @enum {string}
             */
            LoaiTaiKhoan?: "ADMIN" | "CHU_CLB" | "SINH_VIEN";
            /**
             * @description Account status
             * @enum {string}
             */
            TrangThai?: "HOAT_DONG" | "KHOA" | "CHO_DUYET";
            /** Format: date-time */
            createdAt?: string;
        };
        AuthTokens: {
            /** @description JWT access token */
            accessToken?: string;
            /** @description JWT refresh token */
            refreshToken?: string;
        };
        AuthResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                accessToken?: string;
                refreshToken?: string;
                user?: components["schemas"]["UserProfile"];
            };
        };
        Notification: {
            /** @description Notification ID */
            MaThongBao?: string;
            /** @description Title */
            TieuDe?: string;
            /** @description Content */
            NoiDung?: string;
            /**
             * @description Notification type
             * @enum {string}
             */
            LoaiThongBao?: "HE_THONG" | "HOAT_DONG" | "CLB" | "TUYEN_DUNG";
            /**
             * @description Read status
             * @enum {string}
             */
            TrangThai?: "CHUA_DOC" | "DA_DOC";
            /** Format: date-time */
            createdAt?: string;
        };
        NotificationStats: {
            /** @description Total notifications */
            total?: number;
            /** @description Unread count */
            unread?: number;
            /** @description Read count */
            read?: number;
        };
        OverviewStats: {
            totalUsers?: number;
            totalClubs?: number;
            totalEvents?: number;
            totalRegistrations?: number;
        };
        ActivityStats: {
            month?: string;
            events?: number;
            registrations?: number;
        };
    };
    responses: {
        /** @description Authentication required or token invalid/expired */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": "Token không hợp lệ"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Insufficient permissions for this action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": "Bạn không có quyền thực hiện thao tác này"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Request body failed validation */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": "Dữ liệu không hợp lệ"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": "Không tìm thấy tài nguyên"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
