services:
  postgres:
    image: postgres:16
    container_name: clb_database_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: clb_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./environment/database/schema_init.sql:/docker-entrypoint-initdb.d/01_schema_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d clb_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: clb_redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    name: clb_postgres_data
  redis_data:
    name: clb_redis_data